apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - 169.254.169.254 # GCE metadata server
  - metadata.google # GCE metadata server
  - metadata.google.internal # GCE metadata server
  - accounts.google.com # Used to get token
  - "*.googleapis.com"
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  - name: https
    number: 443
    protocol: HTTPS
  resolution: NONE
